apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-flask-app-service
spec:
  selector:
    app: sentiment-analysis-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-mysql-db-service
spec:
  selector:
    app: sentiment-analysis-mysql-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer
